// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/api/v1/models"
)

// DeleteClusterNodesNeighOKCode is the HTTP code returned for type DeleteClusterNodesNeighOK
const DeleteClusterNodesNeighOKCode int = 200

/*DeleteClusterNodesNeighOK Success

swagger:response deleteClusterNodesNeighOK
*/
type DeleteClusterNodesNeighOK struct {
}

// NewDeleteClusterNodesNeighOK creates DeleteClusterNodesNeighOK with default headers values
func NewDeleteClusterNodesNeighOK() *DeleteClusterNodesNeighOK {

	return &DeleteClusterNodesNeighOK{}
}

// WriteResponse to the client
func (o *DeleteClusterNodesNeighOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteClusterNodesNeighErrorsCode is the HTTP code returned for type DeleteClusterNodesNeighErrors
const DeleteClusterNodesNeighErrorsCode int = 206

/*DeleteClusterNodesNeighErrors Deleted with a number of errors encountered

swagger:response deleteClusterNodesNeighErrors
*/
type DeleteClusterNodesNeighErrors struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewDeleteClusterNodesNeighErrors creates DeleteClusterNodesNeighErrors with default headers values
func NewDeleteClusterNodesNeighErrors() *DeleteClusterNodesNeighErrors {

	return &DeleteClusterNodesNeighErrors{}
}

// WithPayload adds the payload to the delete cluster nodes neigh errors response
func (o *DeleteClusterNodesNeighErrors) WithPayload(payload int64) *DeleteClusterNodesNeighErrors {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster nodes neigh errors response
func (o *DeleteClusterNodesNeighErrors) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterNodesNeighErrors) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(206)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteClusterNodesNeighInvalidCode is the HTTP code returned for type DeleteClusterNodesNeighInvalid
const DeleteClusterNodesNeighInvalidCode int = 400

/*DeleteClusterNodesNeighInvalid Invalid endpoint ID format for specified type. Details in error
message


swagger:response deleteClusterNodesNeighInvalid
*/
type DeleteClusterNodesNeighInvalid struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteClusterNodesNeighInvalid creates DeleteClusterNodesNeighInvalid with default headers values
func NewDeleteClusterNodesNeighInvalid() *DeleteClusterNodesNeighInvalid {

	return &DeleteClusterNodesNeighInvalid{}
}

// WithPayload adds the payload to the delete cluster nodes neigh invalid response
func (o *DeleteClusterNodesNeighInvalid) WithPayload(payload models.Error) *DeleteClusterNodesNeighInvalid {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster nodes neigh invalid response
func (o *DeleteClusterNodesNeighInvalid) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterNodesNeighInvalid) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteClusterNodesNeighNotFoundCode is the HTTP code returned for type DeleteClusterNodesNeighNotFound
const DeleteClusterNodesNeighNotFoundCode int = 404

/*DeleteClusterNodesNeighNotFound Endpoint not found

swagger:response deleteClusterNodesNeighNotFound
*/
type DeleteClusterNodesNeighNotFound struct {
}

// NewDeleteClusterNodesNeighNotFound creates DeleteClusterNodesNeighNotFound with default headers values
func NewDeleteClusterNodesNeighNotFound() *DeleteClusterNodesNeighNotFound {

	return &DeleteClusterNodesNeighNotFound{}
}

// WriteResponse to the client
func (o *DeleteClusterNodesNeighNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
