// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/cilium/api/v1/models"
)

// PutClusterNodesNeighReader is a Reader for the PutClusterNodesNeigh structure.
type PutClusterNodesNeighReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutClusterNodesNeighReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutClusterNodesNeighCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutClusterNodesNeighInvalid()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutClusterNodesNeighExists()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutClusterNodesNeighFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutClusterNodesNeighCreated creates a PutClusterNodesNeighCreated with default headers values
func NewPutClusterNodesNeighCreated() *PutClusterNodesNeighCreated {
	return &PutClusterNodesNeighCreated{}
}

/*PutClusterNodesNeighCreated handles this case with default header values.

Created
*/
type PutClusterNodesNeighCreated struct {
}

func (o *PutClusterNodesNeighCreated) Error() string {
	return fmt.Sprintf("[PUT /cluster/nodes/neigh][%d] putClusterNodesNeighCreated ", 201)
}

func (o *PutClusterNodesNeighCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutClusterNodesNeighInvalid creates a PutClusterNodesNeighInvalid with default headers values
func NewPutClusterNodesNeighInvalid() *PutClusterNodesNeighInvalid {
	return &PutClusterNodesNeighInvalid{}
}

/*PutClusterNodesNeighInvalid handles this case with default header values.

Invalid endpoint in request
*/
type PutClusterNodesNeighInvalid struct {
	Payload models.Error
}

func (o *PutClusterNodesNeighInvalid) Error() string {
	return fmt.Sprintf("[PUT /cluster/nodes/neigh][%d] putClusterNodesNeighInvalid  %+v", 400, o.Payload)
}

func (o *PutClusterNodesNeighInvalid) GetPayload() models.Error {
	return o.Payload
}

func (o *PutClusterNodesNeighInvalid) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutClusterNodesNeighExists creates a PutClusterNodesNeighExists with default headers values
func NewPutClusterNodesNeighExists() *PutClusterNodesNeighExists {
	return &PutClusterNodesNeighExists{}
}

/*PutClusterNodesNeighExists handles this case with default header values.

Endpoint already exists
*/
type PutClusterNodesNeighExists struct {
}

func (o *PutClusterNodesNeighExists) Error() string {
	return fmt.Sprintf("[PUT /cluster/nodes/neigh][%d] putClusterNodesNeighExists ", 409)
}

func (o *PutClusterNodesNeighExists) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutClusterNodesNeighFailed creates a PutClusterNodesNeighFailed with default headers values
func NewPutClusterNodesNeighFailed() *PutClusterNodesNeighFailed {
	return &PutClusterNodesNeighFailed{}
}

/*PutClusterNodesNeighFailed handles this case with default header values.

Endpoint creation failed
*/
type PutClusterNodesNeighFailed struct {
	Payload models.Error
}

func (o *PutClusterNodesNeighFailed) Error() string {
	return fmt.Sprintf("[PUT /cluster/nodes/neigh][%d] putClusterNodesNeighFailed  %+v", 500, o.Payload)
}

func (o *PutClusterNodesNeighFailed) GetPayload() models.Error {
	return o.Payload
}

func (o *PutClusterNodesNeighFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
